# Этап сборки
FROM node:20-alpine as build

WORKDIR /docs
COPY docs/package*.json ./
RUN npm install
COPY docs ./
RUN npm run build

# Этап деплоя
FROM nginx:stable-perl

# Копируем собранную документацию из build-этапа в папку Nginx
COPY --from=build /docs/.vitepress/dist /usr/share/nginx/html

# Копируем конфигурацию Nginx
COPY ./containers/nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Указываем, что контейнер будет слушать на порту 5173
EXPOSE 5173

# Запускаем Nginx
CMD ["nginx", "-g", "daemon off;"]
