# Базовый образ Node.js для сборки
FROM node:20 AS build

# Рабочая директория
WORKDIR /usr/src/app

# Копирование package.json и установка зависимостей
COPY package*.json ./
RUN npm install

# Копирование исходного кода
COPY . .

# Сборка Quasar
RUN npm run build

# Финальный образ Nginx
FROM nginx:alpine

# Копирование собранных файлов из предыдущей стадии
COPY --from=build /usr/src/app/dist/spa /usr/share/nginx/html

# Команда запуска Nginx
CMD ["nginx", "-g", "daemon off;"]
