# Используем Node.js образ с Alpine для лёгкости
FROM node:20-alpine

# Устанавливаем рабочую директорию
WORKDIR /usr/src/app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код приложения в контейнер
COPY . .

# Сборка проекта (если используется TypeScript в NestJS)
RUN npm run build

# Устанавливаем утилиту для проверки доступности базы данных (netcat)
RUN apk add --no-cache netcat-openbsd

# Ожидаем подключения к базе данных перед выполнением миграций
CMD ["sh", "-c", "until nc -z -v -w30 db 5432; do echo 'Waiting for database connection...'; sleep 1; done && npx sequelize-cli db:migrate && npm run start:prod"]
