# Базовый образ Node.js
FROM node:20

# Рабочая директория контейнера
WORKDIR /usr/src/app

# Копирование package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Установка зависимостей
RUN npm install

# Копирование всего кода приложения в контейнер
COPY . .

# Открытие порта 3000
EXPOSE 3000

# Команда для запуска приложения
CMD ["npm", "start"]